import type { Metadata } from "next";
import {  Red_Hat_Text } from "next/font/google";
import "./globals.css";

const redHatText = Red_Hat_Text({
  subsets: ["latin"], // Pilih subset yang diinginkan (latin di sini)
  weight: ["400", "700"], // Bisa memilih bobot font yang diinginkan
  variable: "--font-red-hat-text", // Opsional: memberi variable custom untuk font
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${redHatText.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
